version: "3.8"
services:


  angularf:
    image: miralbarhoumi1/devopsprojectfront:latest
    container_name: angularf
    env_file: ./.env
    ports:
      - $ANGULAR_LOCAL_PORT:$ANGULAR_DOCKER_PORT
    links:
      - springboot-be


volumes:
  db:
